/**
 * Native 32×32 HUD / trap stills. One character is one pixel.
 * Run: node --experimental-strip-types tools/art/draw-hud-icons.ts
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PNG } from 'pngjs';

const SIZE = 32;

type Rgba = readonly [number, number, number, number];

const PALETTE = {
  '.': [0, 0, 0, 0],
  X: [22, 22, 32, 255],
  // shared yellow lid / badge / flame core
  Y: [240, 192, 48, 255],
  y: [196, 144, 24, 255],
  // oil body
  L: [122, 128, 140, 255],
  M: [74, 78, 86, 255],
  R: [42, 46, 52, 255],
  u: [107, 68, 35, 255],
  // gasoline body
  A: [224, 96, 72, 255],
  B: [196, 58, 40, 255],
  C: [122, 32, 20, 255],
  v: [107, 58, 32, 255],
  // turbo
  T: [255, 180, 74, 255],
  O: [255, 122, 40, 255],
  D: [184, 60, 16, 255],
  S: [200, 204, 212, 255],
  s: [90, 96, 112, 255],
  F: [255, 224, 102, 255],
  f: [255, 64, 32, 255],
  // missile
  H: [255, 244, 180, 255],
  G: [255, 214, 70, 255],
  N: [210, 120, 24, 255],
  P: [255, 72, 48, 255],
  I: [48, 56, 72, 255],
  E: [255, 140, 40, 255],
  e: [255, 90, 32, 255],
  // mine
  K: [144, 150, 164, 255],
  J: [106, 112, 128, 255],
  Q: [58, 62, 70, 255],
  W: [30, 32, 38, 255],
  Z: [255, 60, 50, 255],
  z: [120, 24, 24, 255],
  // jump
  k: [74, 74, 84, 255],
  m: [42, 42, 48, 255],
  c: [216, 220, 228, 255],
  d: [122, 128, 140, 255],
  w: [232, 240, 244, 255],
} as const satisfies Record<string, Rgba>;

function paint(map: string): Uint8Array {
  const rows = map.trim().split('\n');
  if (rows.length !== SIZE) {
    throw new Error(`map has ${rows.length} rows, want ${SIZE}`);
  }
  const px = new Uint8Array(SIZE * SIZE * 4);
  for (let y = 0; y < SIZE; y += 1) {
    const row = rows[y] ?? '';
    if (row.length !== SIZE) {
      throw new Error(`row ${y} has ${row.length} cols, want ${SIZE}`);
    }
    for (let x = 0; x < SIZE; x += 1) {
      const key = row[x] ?? '.';
      const colour = PALETTE[key as keyof typeof PALETTE];
      if (colour === undefined) {
        throw new Error(`unknown pixel '${key}' at ${x},${y}`);
      }
      const index = (y * SIZE + x) * 4;
      px[index] = colour[0];
      px[index + 1] = colour[1];
      px[index + 2] = colour[2];
      px[index + 3] = colour[3];
    }
  }
  return px;
}

function writePng(path: string, px: Uint8Array): void {
  const png = new PNG({ width: SIZE, height: SIZE });
  png.data.set(px);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, PNG.sync.write(png));
}

function preview4x(px: Uint8Array): Uint8Array {
  const out = new Uint8Array(SIZE * 4 * SIZE * 4 * 4);
  for (let y = 0; y < SIZE; y += 1) {
    for (let x = 0; x < SIZE; x += 1) {
      const src = (y * SIZE + x) * 4;
      for (let dy = 0; dy < 4; dy += 1) {
        for (let dx = 0; dx < 4; dx += 1) {
          const dest = ((y * 4 + dy) * SIZE * 4 + (x * 4 + dx)) * 4;
          out[dest] = px[src] ?? 0;
          out[dest + 1] = px[src + 1] ?? 0;
          out[dest + 2] = px[src + 2] ?? 0;
          out[dest + 3] = px[src + 3] ?? 0;
        }
      }
    }
  }
  return out;
}

function writePreview(path: string, px: Uint8Array): void {
  const png = new PNG({ width: SIZE * 4, height: SIZE * 4 });
  png.data.set(preview4x(px));
  writeFileSync(path, PNG.sync.write(png));
}

// 2px margin. Outline is painted (X), not inferred.

const TURBO = `
................................
................................
................................
................................
................FF..............
...............FfFf.............
................ff..............
..............XssSX.............
.............XsSSSsX............
..............sSSSs.............
...........XXXXXXXXXX...........
..........XTTOOOOOODDX..........
.........XTTOOOOOOODDX..........
.........XTTOOOOOOODDX..........
.........XTTOOOOOOODDX..........
.........XTTOOFFOOODDX..........
.........XTTOOOOOOODDX..........
.........XTTOOOOOOODDX..........
.........XTTOOOOOOODDX..........
.........XTTOOOOOOODDX..........
..........XssSSSSSssX...........
...........XXXXXXXXX............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

const MISSILE = `
................................
................................
................................
................................
................................
......Ee.I......................
.....EeEIINX....................
....XNNGGGHX....................
.....XNGGGGHX...................
......XGGGGGHX..................
.......XNGGGGHX.................
........XGGGGGHX................
.........XNGGGGHX...............
..........XGGGGPPX..............
...........XNGGGPPX.............
............XGGGPPX.............
.............XNPPPX.............
..............XPPP..............
...............XP...............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

const MINE = `
................................
................................
................................
................................
................................
...............zZ...............
..............XZX...............
.........z...XKKKX...z..........
........XZX.XJJQQWX.XZX.........
.........X.XJJQQQWWX.X..........
........XXJJJQQQQWWWWXX.........
.......XKJJJQQQQQQWWWKKX........
......XKJJJQQZZZQQQWWWKKX.......
......XKJJJQQZZZQQQWWWKKX.......
.......XKJJQQQZQWWWKKX..........
........XXJJQQQQWWXX............
.........X.XJQQWWX.X............
........XZX.XKKKX.XZX...........
.........z...XZX...z............
...............z................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

const OIL = `
................................
................................
................................
................................
................................
................................
..........XXXXXXXX..............
.........XYYYYYYYyX.............
........XYYYYYYYYyyX............
.......XYYYYYRYYYYyyX...........
.......XYYYYYYYYYYyyX...........
.......XRRRRRRRRRRRRX...........
.......XLLLMMMMMMRRRX...........
.......XLLLMMMMMMRRRX...........
.......XRRRRRRRRRRRRX...........
.......XLLL.YYYY.RRRX...........
.......XLLLYX..XYRRRX...........
.......XLLLYX..XYRRRX...........
.......XLLL.YXXY.RRRX...........
.......XLLL..YY..RRRX...........
.......XRRRRRRRRRRRRX...........
.......XLLLMMMMMMuRRX...........
.......XLLLMMMMMMRRRX...........
........XXXXXXXXXXX.............
................................
................................
................................
................................
................................
................................
................................
................................
`;

const GAS = `
................................
................................
................................
................................
................................
................................
..........XXXXXXXX..............
.........XYYYYYYYyX.............
........XYYYYYYYYyyX............
.......XYYYYYRYYYYyyX...........
.......XYYYYYYYYYYyyX...........
.......XCCCCCCCCCCCCX...........
.......XAABBBBBBBCCCX...........
.......XAABBBBBBBCCCX...........
.......XCCCCCCCCCCCCX...........
.......XAAB..YY..CCCX...........
.......XAAB.YXXY.CCCX...........
.......XAABYXXXYYCCCX...........
.......XAABYYYYYYCCCX...........
.......XAAB.YYYY.CCCX...........
.......XCCCCCCCCCCCCX...........
.......XAABBBBBBvCCCX...........
.......XAABBBBBBBCCCX...........
........XXXXXXXXXXX.............
................................
................................
................................
................................
................................
................................
................................
................................
`;

const JUMP = `
................................
................................
................................
................................
.................XXX............
................XmcmX...........
...............XmcccmX..........
................XcccX...........
...............XkkmmX...........
..............XkkmmmmX..........
...............XcddcX...........
..............XkkmmmmX..........
.............XwkwmmmwX..........
..............XwwwcX............
.............XkkmmmmX...........
..............XcddcX............
.............XkkmmmmX...........
..............XkkmmX............
...............XcccX............
..............XmcccmX...........
...............XmcmX............
................XXX.............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

const here = dirname(fileURLToPath(import.meta.url));
const hudDir = join(here, '..', '..', 'public', 'assets', 'ui', 'hud');
const trapsDir = join(here, '..', '..', 'public', 'assets', 'traps');
const previewDir = join(here, '..', '..', '.preview', 'hud-icons');

const jobs = [
  { file: 'hud-turbo.png', pixels: paint(TURBO) },
  { file: 'hud-missile.png', pixels: paint(MISSILE) },
  { file: 'hud-mine.png', pixels: paint(MINE) },
  { file: 'hud-oil.png', pixels: paint(OIL) },
  { file: 'hud-jump.png', pixels: paint(JUMP) },
  { file: 'world-gasoline.png', pixels: paint(GAS) },
];

mkdirSync(previewDir, { recursive: true });
for (const job of jobs) {
  writePng(join(hudDir, job.file), job.pixels);
  writePreview(join(previewDir, job.file), job.pixels);
  console.log(`wrote ${job.file}`);
}

const gas = paint(GAS);
writePng(join(trapsDir, 'gasoline.png'), gas);
writePreview(join(previewDir, 'traps-gasoline.png'), gas);
console.log('wrote traps/gasoline.png');
