/**
 * Converts keyboard input into InputCommand objects for the simulation.
 *
 * Every car—human or AI—moves exclusively through InputCommand emission to stepVehicle.
 * The keyboard driver is the human's only interface to that shared code path. This means
 * we must not cheat: there is no direct velocity manipulation, no special-case player
 * logic, no state stored in the adapter. We emit one command per call; stepVehicle
 * sanitizes it (and would catch mistakes if we tried).
 *
 * Brake and reverse are managed by ReverseLatch: while holding the down key and moving
 * forward, brake is 1. Once stopped and the key is still held for engageDelaySeconds
 * (default 0.3 s), reverse engages (brake 0, reverse 1). Pressing up immediately
 * disengages and returns both to 0. This gives responsive one-button control: stab the
 * brake to slow down, or hold to back up after stopping.
 *
 * One subtle design: the screen-space projection mirrors rotation. The world's +Y points
 * LEFT (decision 13), and positive steer is a LEFT turn. But on the isometric screen,
 * that looks like a RIGHT turn due to the y-DOWN coordinate flip in the projection's
 * cross product. So when the player presses the LEFT arrow key (meaning "turn the car
 * left on screen"), they are asking for a NEGATIVE steer in world space. We import
 * SCREEN_ROTATION_SIGN from IsoProjection to express this inversion explicitly so that
 * a future reader does not "fix" it as an inverted-controls bug. It is not a bug; it is
 * the correct world-space steering generated by the projection's mathematics.
 *
 * Key bindings:
 *   Up / W        = throttle (0 or 1); also disengages reverse if held
 *   Down / S      = brake (0 or 1); becomes reverse (0.35× max speed) when held at standstill
 *   Left / A      = steer SCREEN_ROTATION_SIGN * 1 = -1 (a RIGHT turn in world space,
 *                   which the mirrored projection draws as a LEFT turn on screen)
 *   Right / D     = steer SCREEN_ROTATION_SIGN * -1 = +1 (a LEFT turn in world space,
 *                   drawn as a RIGHT turn on screen)
 *   Space         = fire (boolean)
 *   Ctrl / Shift  = dropMine (boolean)
 *
 * If neither or both horizontal keys are held, steer is 0.
 */

import Phaser from 'phaser';
import type { InputCommand } from '../../domain/input/InputCommand.ts';
import { SCREEN_ROTATION_SIGN } from '../render/IsoProjection.ts';
import { ReverseLatch } from './ReverseLatch.ts';

export class KeyboardDriver {
  private readonly keyboardPlugin: Phaser.Input.Keyboard.KeyboardPlugin;
  private readonly keyUp: Phaser.Input.Keyboard.Key;
  private readonly keyDown: Phaser.Input.Keyboard.Key;
  private readonly keyLeft: Phaser.Input.Keyboard.Key;
  private readonly keyRight: Phaser.Input.Keyboard.Key;
  private readonly keyW: Phaser.Input.Keyboard.Key;
  private readonly keyS: Phaser.Input.Keyboard.Key;
  private readonly keyA: Phaser.Input.Keyboard.Key;
  private readonly keyD: Phaser.Input.Keyboard.Key;
  private readonly keySpace: Phaser.Input.Keyboard.Key;
  private readonly keyCtrl: Phaser.Input.Keyboard.Key;
  private readonly keyShift: Phaser.Input.Keyboard.Key;
  private readonly reverseLatch: ReverseLatch;

  constructor(keyboard: Phaser.Input.Keyboard.KeyboardPlugin) {
    if (!keyboard) {
      throw new Error(
        'KeyboardDriver: keyboard plugin is null or undefined. '
        + 'This usually means the Keyboard plugin is disabled in the scene config. '
        + 'Ensure "input: { keyboard: true }" is set in the scene init.',
      );
    }

    this.keyboardPlugin = keyboard;
    this.reverseLatch = new ReverseLatch();

    // Register all keys at once so we can poll them cheaply in read().
    this.keyUp = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.UP);
    this.keyDown = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.DOWN);
    this.keyLeft = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.LEFT);
    this.keyRight = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.RIGHT);
    this.keyW = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.W);
    this.keyS = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.S);
    this.keyA = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.A);
    this.keyD = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.D);
    this.keySpace = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);
    this.keyCtrl = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.CTRL);
    this.keyShift = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SHIFT);
  }

  /**
   * Read the current keyboard state and produce an InputCommand.
   *
   * This is cheap: we only inspect the registered Key objects' isDown flags,
   * thread the brake key and car speed through ReverseLatch for brake→reverse logic,
   * and return a fresh InputCommand. No per-frame listeners, no state mutation,
   * no allocation beyond the returned object.
   *
   * @param deltaSeconds - elapsed time since last update (passed to ReverseLatch for dwell timing)
   * @param forwardSpeed - the car's current forward velocity (passed to ReverseLatch to detect standstill)
   *
   * Values are already in range (throttle/brake/reverse 0..1, steer -1..0..+1), so
   * sanitizeInput is unnecessary. stepVehicle will call it anyway as a guard
   * against a misbehaving adapter, so we save the redundant clamp here.
   */
  read(deltaSeconds: number, forwardSpeed: number): InputCommand {
    const throttle = this.keyUp.isDown || this.keyW.isDown ? 1 : 0;

    // Brake and reverse are managed by the latch, not read directly.
    const downHeld = this.keyDown.isDown || this.keyS.isDown;
    const upHeld = this.keyUp.isDown || this.keyW.isDown;
    const driveIntent = this.reverseLatch.update(downHeld, upHeld, forwardSpeed, deltaSeconds);

    // Steer: one sign if only left is held, the other if only right is held, 0 if
    // neither or both. The projection mirrors rotation (SCREEN_ROTATION_SIGN = -1):
    //   pressing LEFT  -> SCREEN_ROTATION_SIGN *  1 = -1, a world CLOCKWISE turn,
    //                     which is drawn rotating anticlockwise, i.e. towards screen-left
    //   pressing RIGHT -> SCREEN_ROTATION_SIGN * -1 = +1, a world LEFT turn,
    //                     drawn rotating towards screen-right
    const leftPressed = this.keyLeft.isDown || this.keyA.isDown;
    const rightPressed = this.keyRight.isDown || this.keyD.isDown;
    let steer = 0;
    if (leftPressed && !rightPressed) {
      steer = SCREEN_ROTATION_SIGN * 1;
    } else if (rightPressed && !leftPressed) {
      steer = SCREEN_ROTATION_SIGN * -1;
    }

    const fire = this.keySpace.isDown;
    const dropMine = this.keyCtrl.isDown || this.keyShift.isDown;

    return {
      throttle,
      brake: driveIntent.brake,
      steer,
      reverse: driveIntent.reverse,
      fire,
      dropMine,
    };
  }

  /**
   * Clean up: remove all registered keys so a scene restart does not leak or
   * double-register them.
   */
  destroy(): void {
    this.keyboardPlugin.removeKey(this.keyUp);
    this.keyboardPlugin.removeKey(this.keyDown);
    this.keyboardPlugin.removeKey(this.keyLeft);
    this.keyboardPlugin.removeKey(this.keyRight);
    this.keyboardPlugin.removeKey(this.keyW);
    this.keyboardPlugin.removeKey(this.keyS);
    this.keyboardPlugin.removeKey(this.keyA);
    this.keyboardPlugin.removeKey(this.keyD);
    this.keyboardPlugin.removeKey(this.keySpace);
    this.keyboardPlugin.removeKey(this.keyCtrl);
    this.keyboardPlugin.removeKey(this.keyShift);
  }
}
