/**
 * Converts keyboard input into InputCommand objects for the simulation.
 *
 * Every car—human or AI—moves exclusively through InputCommand emission to stepVehicle.
 * The keyboard driver is the human's only interface to that shared code path. This means
 * we must not cheat: there is no direct velocity manipulation, no special-case player
 * logic, no state stored in the adapter. We emit one command per call; stepVehicle
 * sanitizes it (and would catch mistakes if we tried).
 *
 * Brake and reverse are managed by ReverseLatch: while holding the down key and moving
 * forward, brake is 1. Once stopped and the key is still held for engageDelaySeconds
 * (default 0.3 s), reverse engages (brake 0, reverse 1). Pressing up immediately
 * disengages and returns both to 0. This gives responsive one-button control: stab the
 * brake to slow down, or hold to back up after stopping.
 *
 * One subtle design: the screen-space projection mirrors rotation. The world's +Y points
 * LEFT (decision 13), and positive steer is a LEFT turn. But on the isometric screen,
 * that looks like a RIGHT turn due to the y-DOWN coordinate flip in the projection's
 * cross product. So when the player presses the LEFT arrow key (meaning "turn the car
 * left on screen"), they are asking for a NEGATIVE steer in world space. We import
 * SCREEN_ROTATION_SIGN from IsoProjection to express this inversion explicitly so that
 * a future reader does not "fix" it as an inverted-controls bug. It is not a bug; it is
 * the correct world-space steering generated by the projection's mathematics.
 *
 * Key bindings (console pad):
 *   Up            = throttle (0 or 1); also disengages reverse if held
 *   Down          = brake (0 or 1); becomes reverse (0.35× max speed) when held at standstill
 *   Left          = steer SCREEN_ROTATION_SIGN * 1 = -1 (a RIGHT turn in world space,
 *                   which the mirrored projection draws as a LEFT turn on screen)
 *   Right         = steer SCREEN_ROTATION_SIGN * -1 = +1 (a LEFT turn in world space,
 *                   drawn as a RIGHT turn on screen)
 *   C             = fire missile (edge-triggered)
 *   Z             = drop oil (edge-triggered)
 *   X             = drop landmine (edge-triggered)
 *   Left Shift / A = turbo (hold; 4 charges, +35% for 2s). Hold, not tap:
 *                   JustDown is eaten if Shift is pressed during countdown.
 *   Space         = hop (edge-triggered; 4 charges, refill at the line)
 *
 * Movement is arrows only so C/X/Z can be the weapon buttons without
 * fighting the steering. If neither or both horizontal keys are held, steer is 0.
 */

import Phaser from 'phaser';
import type { InputCommand } from '../../domain/input/InputCommand.ts';
import { SCREEN_ROTATION_SIGN } from '../render/IsoProjection.ts';
import { ReverseLatch } from './ReverseLatch.ts';

export class KeyboardDriver {
  private readonly keyboardPlugin: Phaser.Input.Keyboard.KeyboardPlugin;
  private readonly keyUp: Phaser.Input.Keyboard.Key;
  private readonly keyDown: Phaser.Input.Keyboard.Key;
  private readonly keyLeft: Phaser.Input.Keyboard.Key;
  private readonly keyRight: Phaser.Input.Keyboard.Key;
  private readonly keyMissile: Phaser.Input.Keyboard.Key;
  private readonly keyOil: Phaser.Input.Keyboard.Key;
  private readonly keyMine: Phaser.Input.Keyboard.Key;
  private readonly keyJump: Phaser.Input.Keyboard.Key;
  private readonly keyTurbo: Phaser.Input.Keyboard.Key;
  private readonly keyTurboAlt: Phaser.Input.Keyboard.Key;
  private readonly reverseLatch: ReverseLatch;

  constructor(keyboard: Phaser.Input.Keyboard.KeyboardPlugin) {
    if (!keyboard) {
      throw new Error(
        'KeyboardDriver: keyboard plugin is null or undefined. '
        + 'This usually means the Keyboard plugin is disabled in the scene config. '
        + 'Ensure "input: { keyboard: true }" is set in the scene init.',
      );
    }

    this.keyboardPlugin = keyboard;
    this.reverseLatch = new ReverseLatch();

    this.keyUp = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.UP);
    this.keyDown = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.DOWN);
    this.keyLeft = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.LEFT);
    this.keyRight = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.RIGHT);
    this.keyMissile = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.C);
    this.keyOil = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.Z);
    this.keyMine = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.X);
    this.keyJump = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);
    this.keyTurbo = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SHIFT);
    this.keyTurboAlt = keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.A);
  }

  /**
   * Read the current keyboard state and produce an InputCommand.
   *
   * Weapon keys use Phaser's JustDown so a held button cannot empty the inventory
   * in a single frame of 60 simulation steps.
   */
  read(deltaSeconds: number, forwardSpeed: number): InputCommand {
    const throttle = this.keyUp.isDown ? 1 : 0;

    const downHeld = this.keyDown.isDown;
    const upHeld = this.keyUp.isDown;
    const driveIntent = this.reverseLatch.update(downHeld, upHeld, forwardSpeed, deltaSeconds);

    const leftPressed = this.keyLeft.isDown;
    const rightPressed = this.keyRight.isDown;
    let steer = 0;
    if (leftPressed && !rightPressed) {
      steer = SCREEN_ROTATION_SIGN * 1;
    } else if (rightPressed && !leftPressed) {
      steer = SCREEN_ROTATION_SIGN * -1;
    }

    return {
      throttle,
      brake: driveIntent.brake,
      steer,
      reverse: driveIntent.reverse,
      fire: Phaser.Input.Keyboard.JustDown(this.keyMissile),
      dropOil: Phaser.Input.Keyboard.JustDown(this.keyOil),
      dropMine: Phaser.Input.Keyboard.JustDown(this.keyMine),
      jump: Phaser.Input.Keyboard.JustDown(this.keyJump),
      // isDown, not JustDown: the gauge burns while held.
      boost: this.keyTurbo.isDown || this.keyTurboAlt.isDown,
    };
  }

  destroy(): void {
    this.keyboardPlugin.removeKey(this.keyUp);
    this.keyboardPlugin.removeKey(this.keyDown);
    this.keyboardPlugin.removeKey(this.keyLeft);
    this.keyboardPlugin.removeKey(this.keyRight);
    this.keyboardPlugin.removeKey(this.keyMissile);
    this.keyboardPlugin.removeKey(this.keyOil);
    this.keyboardPlugin.removeKey(this.keyMine);
    this.keyboardPlugin.removeKey(this.keyJump);
    this.keyboardPlugin.removeKey(this.keyTurbo);
    this.keyboardPlugin.removeKey(this.keyTurboAlt);
  }
}
